-- =====================================================================
-- Sold It Today | BASELINE (squash) migration — pre-Phase-0 net schema
-- =====================================================================
-- This is a BASELINE, not a set of "original" migrations. It reproduces the
-- exact net PUBLIC schema that production held immediately BEFORE Phase 0.
--
-- Why a baseline exists: the recorded pre-Phase-0 history could not rebuild the
-- database (the `leads` table was created in the Supabase dashboard, never as a
-- migration; the recorded `create_leads_table` used a different shape and was a
-- prod no-op). See supabase/legacy-recovered/ for the authentic recovered bodies
-- and the full explanation.
--
-- How it was built:
--   * Section 1 (leads) is authored to match production's REAL leads table
--     (bigint identity id, "Leads_pkey", nullable columns, the single
--     "Allow anonymous lead submissions" policy) — the part the broken history
--     could not reproduce.
--   * Sections 2-7 are the VERBATIM bodies of the migrations that DID build the
--     rest of production correctly (phase1_portal_schema, phase1b_agent_rls,
--     agent_avatar_url, phase4_buyer_portal, phase4_buyer_photo,
--     phase4b_documents_and_two_way_notes).
--
-- Applying this baseline, then 20260912215211_phase0_org_tenancy_foundation,
-- then 20260912220434_phase0_secdef_hardening, reproduces current production
-- (verified by a catalog-level schema diff).
--
-- Assumes a standard Supabase project (auth + storage schemas, and the anon /
-- authenticated / service_role roles with the usual default privileges already
-- present, exactly as when the original migrations ran).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. leads  (authored to match production's real dashboard-created table)
-- ---------------------------------------------------------------------
create table if not exists public.leads (
  id bigint generated by default as identity constraint "Leads_pkey" primary key,
  created_at timestamptz not null default now(),
  first_name text,
  last_name text,
  email text,
  phone text,
  lead_type text,
  source_page text,
  message text,
  status text,
  notes text,
  follow_up_date date
);

alter table public.leads enable row level security;

create policy "Allow anonymous lead submissions"
  on public.leads for insert
  to anon
  with check (true);

-- ---------------------------------------------------------------------
-- 2. phase1_portal_schema  (verbatim)
-- ---------------------------------------------------------------------
create table if not exists public.agents (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  brand text,
  logo_url text,
  phone text,
  email text,
  license text,
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references public.agents(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  type text not null default 'seller' check (type in ('seller','buyer')),
  created_at timestamptz not null default now()
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references public.agents(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  mls_number text,
  address text not null,
  city text,
  state text,
  zip text,
  price numeric,
  beds int,
  baths numeric,
  sqft int,
  status text not null default 'Active',
  list_date date,
  photo_url text,
  source text not null default 'manual',
  portal_token text not null unique
    default (replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','')),
  created_at timestamptz not null default now()
);

create table if not exists public.engagement_snapshots (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete cascade,
  period_start date,
  period_end date,
  total_views int not null default 0,
  shares int not null default 0,
  favorites int not null default 0,
  returning_pct int,
  by_source jsonb not null default '[]'::jsonb,
  by_city jsonb not null default '[]'::jsonb,
  source text not null default 'listtrac',
  captured_at timestamptz not null default now()
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete cascade,
  body text not null,
  client_visible boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete cascade,
  name text not null,
  storage_path text,
  client_visible boolean not null default true,
  created_at timestamptz not null default now()
);

-- Lock everything down: RLS on, no public policies. Access only via the RPC below.
alter table public.agents enable row level security;
alter table public.clients enable row level security;
alter table public.listings enable row level security;
alter table public.engagement_snapshots enable row level security;
alter table public.notes enable row level security;
alter table public.documents enable row level security;

-- Token-only read for the seller portal. Security definer so it bypasses RLS,
-- but only ever returns the single listing matching the unguessable token.
create or replace function public.get_seller_portal(p_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'listing', jsonb_build_object(
      'address', l.address, 'city', l.city, 'state', l.state, 'zip', l.zip,
      'price', l.price, 'beds', l.beds, 'baths', l.baths, 'sqft', l.sqft,
      'status', l.status, 'mls_number', l.mls_number, 'photo_url', l.photo_url,
      'list_date', l.list_date
    ),
    'agent', jsonb_build_object('name', a.name, 'brand', a.brand, 'phone', a.phone, 'email', a.email),
    'client', jsonb_build_object('name', c.name),
    'stats', (
      select to_jsonb(s) - 'id' - 'listing_id'
      from public.engagement_snapshots s
      where s.listing_id = l.id
      order by s.period_end desc nulls last, s.captured_at desc
      limit 1
    ),
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object('body', n.body, 'created_at', n.created_at) order by n.created_at desc)
      from public.notes n where n.listing_id = l.id and n.client_visible
    ), '[]'::jsonb),
    'documents', coalesce((
      select jsonb_agg(jsonb_build_object('name', d.name, 'storage_path', d.storage_path) order by d.created_at desc)
      from public.documents d where d.listing_id = l.id and d.client_visible
    ), '[]'::jsonb)
  )
  from public.listings l
  left join public.agents a on a.id = l.agent_id
  left join public.clients c on c.id = l.client_id
  where l.portal_token = p_token
  limit 1;
$$;

revoke all on function public.get_seller_portal(text) from public;
grant execute on function public.get_seller_portal(text) to anon, authenticated;

-- ---------------------------------------------------------------------
-- 3. phase1b_agent_rls  (verbatim)
-- ---------------------------------------------------------------------
create or replace function public.current_agent_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from public.agents
  where lower(email) = lower(auth.jwt() ->> 'email')
  limit 1;
$$;

grant execute on function public.current_agent_id() to authenticated;

create policy agents_self_select on public.agents for select to authenticated
  using (id = public.current_agent_id());
create policy agents_self_update on public.agents for update to authenticated
  using (id = public.current_agent_id()) with check (id = public.current_agent_id());

create policy listings_agent_all on public.listings for all to authenticated
  using (agent_id = public.current_agent_id())
  with check (agent_id = public.current_agent_id());

create policy clients_agent_all on public.clients for all to authenticated
  using (agent_id = public.current_agent_id())
  with check (agent_id = public.current_agent_id());

create policy snap_agent_all on public.engagement_snapshots for all to authenticated
  using (listing_id in (select id from public.listings where agent_id = public.current_agent_id()))
  with check (listing_id in (select id from public.listings where agent_id = public.current_agent_id()));

create policy notes_agent_all on public.notes for all to authenticated
  using (listing_id in (select id from public.listings where agent_id = public.current_agent_id()))
  with check (listing_id in (select id from public.listings where agent_id = public.current_agent_id()));

create policy docs_agent_all on public.documents for all to authenticated
  using (listing_id in (select id from public.listings where agent_id = public.current_agent_id()))
  with check (listing_id in (select id from public.listings where agent_id = public.current_agent_id()));

-- ---------------------------------------------------------------------
-- 4. agent_avatar_url  (verbatim)
-- ---------------------------------------------------------------------
alter table public.agents add column if not exists avatar_url text;

create or replace function public.get_seller_portal(p_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'listing', jsonb_build_object(
      'address', l.address, 'city', l.city, 'state', l.state, 'zip', l.zip,
      'price', l.price, 'beds', l.beds, 'baths', l.baths, 'sqft', l.sqft,
      'status', l.status, 'mls_number', l.mls_number, 'photo_url', l.photo_url,
      'list_date', l.list_date
    ),
    'agent', jsonb_build_object('name', a.name, 'brand', a.brand, 'phone', a.phone, 'email', a.email, 'avatar_url', a.avatar_url),
    'client', jsonb_build_object('name', c.name),
    'stats', (
      select to_jsonb(s) - 'id' - 'listing_id'
      from public.engagement_snapshots s
      where s.listing_id = l.id
      order by s.period_end desc nulls last, s.captured_at desc
      limit 1
    ),
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object('body', n.body, 'created_at', n.created_at) order by n.created_at desc)
      from public.notes n where n.listing_id = l.id and n.client_visible
    ), '[]'::jsonb),
    'documents', coalesce((
      select jsonb_agg(jsonb_build_object('name', d.name, 'storage_path', d.storage_path) order by d.created_at desc)
      from public.documents d where d.listing_id = l.id and d.client_visible
    ), '[]'::jsonb)
  )
  from public.listings l
  left join public.agents a on a.id = l.agent_id
  left join public.clients c on c.id = l.client_id
  where l.portal_token = p_token
  limit 1;
$$;

update public.agents set avatar_url = '/assets/team/charlotte-hypes.png'
where lower(email) = 'charlotte@soldittoday.com';

-- ---------------------------------------------------------------------
-- 5. phase4_buyer_portal  (verbatim)
-- ---------------------------------------------------------------------
create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  agent_id uuid references public.agents(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  address text not null,
  city text,
  state text,
  zip text,
  price numeric,
  status text not null default 'Under Contract',
  target_close_date date,
  portal_token text not null unique
    default (replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','')),
  created_at timestamptz not null default now()
);

create table if not exists public.milestones (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid references public.transactions(id) on delete cascade,
  label text not null,
  status text not null default 'upcoming' check (status in ('upcoming','in_progress','done')),
  date date,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.notes add column if not exists transaction_id uuid references public.transactions(id) on delete cascade;

alter table public.transactions enable row level security;
alter table public.milestones enable row level security;

create policy transactions_agent_all on public.transactions for all to authenticated
  using (agent_id = public.current_agent_id())
  with check (agent_id = public.current_agent_id());

create policy milestones_agent_all on public.milestones for all to authenticated
  using (transaction_id in (select id from public.transactions where agent_id = public.current_agent_id()))
  with check (transaction_id in (select id from public.transactions where agent_id = public.current_agent_id()));

drop policy if exists notes_agent_all on public.notes;
create policy notes_agent_all on public.notes for all to authenticated
  using (
    listing_id in (select id from public.listings where agent_id = public.current_agent_id())
    or transaction_id in (select id from public.transactions where agent_id = public.current_agent_id())
  )
  with check (
    listing_id in (select id from public.listings where agent_id = public.current_agent_id())
    or transaction_id in (select id from public.transactions where agent_id = public.current_agent_id())
  );

create or replace function public.get_buyer_portal(p_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'transaction', jsonb_build_object(
      'address', t.address, 'city', t.city, 'state', t.state, 'zip', t.zip,
      'price', t.price, 'status', t.status, 'target_close_date', t.target_close_date
    ),
    'agent', jsonb_build_object('name', a.name, 'brand', a.brand, 'phone', a.phone, 'email', a.email, 'avatar_url', a.avatar_url),
    'client', jsonb_build_object('name', c.name),
    'milestones', coalesce((
      select jsonb_agg(jsonb_build_object('label', m.label, 'status', m.status, 'date', m.date) order by m.sort_order)
      from public.milestones m where m.transaction_id = t.id
    ), '[]'::jsonb),
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object('body', n.body, 'created_at', n.created_at) order by n.created_at desc)
      from public.notes n where n.transaction_id = t.id and n.client_visible
    ), '[]'::jsonb)
  )
  from public.transactions t
  left join public.agents a on a.id = t.agent_id
  left join public.clients c on c.id = t.client_id
  where t.portal_token = p_token
  limit 1;
$$;

revoke all on function public.get_buyer_portal(text) from public;
grant execute on function public.get_buyer_portal(text) to anon, authenticated;

-- ---------------------------------------------------------------------
-- 6. phase4_buyer_photo  (verbatim)
-- ---------------------------------------------------------------------
alter table public.transactions add column if not exists photo_url text;

create or replace function public.get_buyer_portal(p_token text)
returns jsonb
language sql
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'transaction', jsonb_build_object(
      'address', t.address, 'city', t.city, 'state', t.state, 'zip', t.zip,
      'price', t.price, 'status', t.status, 'target_close_date', t.target_close_date,
      'photo_url', t.photo_url
    ),
    'agent', jsonb_build_object('name', a.name, 'brand', a.brand, 'phone', a.phone, 'email', a.email, 'avatar_url', a.avatar_url),
    'client', jsonb_build_object('name', c.name),
    'milestones', coalesce((
      select jsonb_agg(jsonb_build_object('label', m.label, 'status', m.status, 'date', m.date) order by m.sort_order)
      from public.milestones m where m.transaction_id = t.id
    ), '[]'::jsonb),
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object('body', n.body, 'created_at', n.created_at) order by n.created_at desc)
      from public.notes n where n.transaction_id = t.id and n.client_visible
    ), '[]'::jsonb)
  )
  from public.transactions t
  left join public.agents a on a.id = t.agent_id
  left join public.clients c on c.id = t.client_id
  where t.portal_token = p_token
  limit 1;
$$;
grant execute on function public.get_buyer_portal(text) to anon, authenticated;

-- ---------------------------------------------------------------------
-- 7. phase4b_documents_and_two_way_notes  (verbatim)
-- ---------------------------------------------------------------------
alter table public.documents
  add column if not exists transaction_id uuid references public.transactions(id) on delete cascade,
  add column if not exists agent_id uuid references public.agents(id) on delete cascade,
  add column if not exists uploaded_by text not null default 'agent',
  add column if not exists content_type text,
  add column if not exists size_bytes bigint;

alter table public.documents drop constraint if exists documents_uploaded_by_check;
alter table public.documents
  add constraint documents_uploaded_by_check check (uploaded_by in ('agent','buyer'));

create index if not exists documents_transaction_id_idx on public.documents(transaction_id);
create index if not exists documents_agent_id_idx on public.documents(agent_id);

alter table public.documents enable row level security;
drop policy if exists documents_agent_all on public.documents;
create policy documents_agent_all on public.documents
  for all
  using (agent_id = public.current_agent_id())
  with check (agent_id = public.current_agent_id());

alter table public.notes
  add column if not exists from_client boolean not null default false;

insert into storage.buckets (id, name, public)
values ('portal-docs','portal-docs', false)
on conflict (id) do nothing;

create or replace function public.add_buyer_reply(p_token text, p_body text)
returns boolean
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_tx uuid;
begin
  select id into v_tx from public.transactions where portal_token = p_token limit 1;
  if v_tx is null then return false; end if;
  if coalesce(btrim(p_body), '') = '' then return false; end if;
  insert into public.notes (transaction_id, body, client_visible, from_client)
  values (v_tx, left(p_body, 4000), true, true);
  return true;
end;
$function$;
grant execute on function public.add_buyer_reply(text, text) to anon, authenticated;

create or replace function public.get_buyer_portal(p_token text)
returns jsonb
language sql
security definer
set search_path to 'public'
as $function$
  select jsonb_build_object(
    'transaction', jsonb_build_object(
      'address', t.address, 'city', t.city, 'state', t.state, 'zip', t.zip,
      'price', t.price, 'status', t.status, 'target_close_date', t.target_close_date,
      'photo_url', t.photo_url
    ),
    'agent', jsonb_build_object('name', a.name, 'brand', a.brand, 'phone', a.phone, 'email', a.email, 'avatar_url', a.avatar_url),
    'client', jsonb_build_object('name', c.name),
    'milestones', coalesce((
      select jsonb_agg(jsonb_build_object('label', m.label, 'status', m.status, 'date', m.date) order by m.sort_order)
      from public.milestones m where m.transaction_id = t.id
    ), '[]'::jsonb),
    'notes', coalesce((
      select jsonb_agg(jsonb_build_object('body', n.body, 'created_at', n.created_at, 'from_client', n.from_client) order by n.created_at asc)
      from public.notes n
      where n.transaction_id = t.id and (n.client_visible or n.from_client)
    ), '[]'::jsonb),
    'documents', coalesce((
      select jsonb_agg(jsonb_build_object('id', d.id, 'name', d.name, 'uploaded_by', d.uploaded_by, 'created_at', d.created_at) order by d.created_at desc)
      from public.documents d
      where d.transaction_id = t.id and (d.client_visible or d.uploaded_by = 'buyer')
    ), '[]'::jsonb)
  )
  from public.transactions t
  left join public.agents a on a.id = t.agent_id
  left join public.clients c on c.id = t.client_id
  where t.portal_token = p_token
  limit 1;
$function$;
